### ISSUE TITLE
Footsteps sound effect

### ISSUE THREAD

**Issue by Avokadomos** [EpicTypo/ReLeap#28]
There should be audio feedback when running, like footsteps, wind effect or something similar.

**Comment by thedudeleo** [comment]
@Avokadomos there is, maybe it's not loud enough?

**Comment by Avokadomos** [comment]
Okay. I just got the impression that there wasn't when we discussed the game, so I haven't actually checked it out myself. That leaves only the visual effects then.

**Comment by thedudeleo** [comment]
k, archived
